#!/bin/bash
if [ -z "$PYFILE" ]; then 
echo "Error: PYFILE environment variable is not set."
exit 1
fi
filename=$(basename -- "$PYFILE")
filename_noext="${filename%.*}"
python3 -m py_compile "$PYFILE"
if [ $? -eq 0 ]; then
compiled_filename="${filename_noext}.pyc"
echo "Compilation successful. Outputfilename: $compilied_filename" 
else
echo "Compilation failed"
fi
